package com.mycompany.entity;
// Generated Feb 23, 2018 5:59:52 AM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Addresses generated by hbm2java
 */
@Entity
@Table(name="Addresses"
    ,catalog="Project_DB"
)
public class Addresses  implements java.io.Serializable {


     private Integer addressId;
     private Cities cities;
     private Continetes continetes;
     private Countries countries;
     private Districtd districtd;
     private Employees employees;
     private Governrates governrates;
     private UsersAppUserUs usersAppUserUs;
     private String buildingNo;
     private String addressDetails1;
     private String addressDetails2;
     private Integer postalCode;

    public Addresses() {
    }

	
    public Addresses(Cities cities, Continetes continetes, Countries countries, Districtd districtd, Employees employees, Governrates governrates, UsersAppUserUs usersAppUserUs, String buildingNo, String addressDetails1, String addressDetails2) {
        this.cities = cities;
        this.continetes = continetes;
        this.countries = countries;
        this.districtd = districtd;
        this.employees = employees;
        this.governrates = governrates;
        this.usersAppUserUs = usersAppUserUs;
        this.buildingNo = buildingNo;
        this.addressDetails1 = addressDetails1;
        this.addressDetails2 = addressDetails2;
    }
    public Addresses(Cities cities, Continetes continetes, Countries countries, Districtd districtd, Employees employees, Governrates governrates, UsersAppUserUs usersAppUserUs, String buildingNo, String addressDetails1, String addressDetails2, Integer postalCode) {
       this.cities = cities;
       this.continetes = continetes;
       this.countries = countries;
       this.districtd = districtd;
       this.employees = employees;
       this.governrates = governrates;
       this.usersAppUserUs = usersAppUserUs;
       this.buildingNo = buildingNo;
       this.addressDetails1 = addressDetails1;
       this.addressDetails2 = addressDetails2;
       this.postalCode = postalCode;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="Address_Id", unique=true, nullable=false)
    public Integer getAddressId() {
        return this.addressId;
    }
    
    public void setAddressId(Integer addressId) {
        this.addressId = addressId;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="City_Id", nullable=false)
    public Cities getCities() {
        return this.cities;
    }
    
    public void setCities(Cities cities) {
        this.cities = cities;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="Continent_Id", nullable=false)
    public Continetes getContinetes() {
        return this.continetes;
    }
    
    public void setContinetes(Continetes continetes) {
        this.continetes = continetes;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="country_id", nullable=false)
    public Countries getCountries() {
        return this.countries;
    }
    
    public void setCountries(Countries countries) {
        this.countries = countries;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="District_Id", nullable=false)
    public Districtd getDistrictd() {
        return this.districtd;
    }
    
    public void setDistrictd(Districtd districtd) {
        this.districtd = districtd;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="Employee_Id", nullable=false)
    public Employees getEmployees() {
        return this.employees;
    }
    
    public void setEmployees(Employees employees) {
        this.employees = employees;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="governorate_Id", nullable=false)
    public Governrates getGovernrates() {
        return this.governrates;
    }
    
    public void setGovernrates(Governrates governrates) {
        this.governrates = governrates;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="Users_User_id", nullable=false)
    public UsersAppUserUs getUsersAppUserUs() {
        return this.usersAppUserUs;
    }
    
    public void setUsersAppUserUs(UsersAppUserUs usersAppUserUs) {
        this.usersAppUserUs = usersAppUserUs;
    }

    
    @Column(name="Building_no", nullable=false, length=10)
    public String getBuildingNo() {
        return this.buildingNo;
    }
    
    public void setBuildingNo(String buildingNo) {
        this.buildingNo = buildingNo;
    }

    
    @Column(name="Address_Details_1", nullable=false)
    public String getAddressDetails1() {
        return this.addressDetails1;
    }
    
    public void setAddressDetails1(String addressDetails1) {
        this.addressDetails1 = addressDetails1;
    }

    
    @Column(name="Address_Details_2", nullable=false)
    public String getAddressDetails2() {
        return this.addressDetails2;
    }
    
    public void setAddressDetails2(String addressDetails2) {
        this.addressDetails2 = addressDetails2;
    }

    
    @Column(name="Postal_Code")
    public Integer getPostalCode() {
        return this.postalCode;
    }
    
    public void setPostalCode(Integer postalCode) {
        this.postalCode = postalCode;
    }




}


