package com.mycompany.entity;
// Generated Feb 23, 2018 5:59:52 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Cities generated by hbm2java
 */
@Entity
@Table(name="Cities"
    ,catalog="Project_DB"
)
public class Cities  implements java.io.Serializable {


     private Integer cityId;
     private Countries countries;
     private Integer cityCode;
     private Integer cityName;
     private String cityDesc;
     private Set<Addresses> addresseses = new HashSet<Addresses>(0);
     private Set<Districtd> districtds = new HashSet<Districtd>(0);

    public Cities() {
    }

	
    public Cities(Countries countries) {
        this.countries = countries;
    }
    public Cities(Countries countries, Integer cityCode, Integer cityName, String cityDesc, Set<Addresses> addresseses, Set<Districtd> districtds) {
       this.countries = countries;
       this.cityCode = cityCode;
       this.cityName = cityName;
       this.cityDesc = cityDesc;
       this.addresseses = addresseses;
       this.districtds = districtds;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="City_Id", unique=true, nullable=false)
    public Integer getCityId() {
        return this.cityId;
    }
    
    public void setCityId(Integer cityId) {
        this.cityId = cityId;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="country_id", nullable=false)
    public Countries getCountries() {
        return this.countries;
    }
    
    public void setCountries(Countries countries) {
        this.countries = countries;
    }

    
    @Column(name="City_Code")
    public Integer getCityCode() {
        return this.cityCode;
    }
    
    public void setCityCode(Integer cityCode) {
        this.cityCode = cityCode;
    }

    
    @Column(name="City_Name")
    public Integer getCityName() {
        return this.cityName;
    }
    
    public void setCityName(Integer cityName) {
        this.cityName = cityName;
    }

    
    @Column(name="City_Desc", length=300)
    public String getCityDesc() {
        return this.cityDesc;
    }
    
    public void setCityDesc(String cityDesc) {
        this.cityDesc = cityDesc;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="cities")
    public Set<Addresses> getAddresseses() {
        return this.addresseses;
    }
    
    public void setAddresseses(Set<Addresses> addresseses) {
        this.addresseses = addresseses;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="cities")
    public Set<Districtd> getDistrictds() {
        return this.districtds;
    }
    
    public void setDistrictds(Set<Districtd> districtds) {
        this.districtds = districtds;
    }




}


