package com.mycompany.entity;
// Generated Feb 23, 2018 5:59:52 AM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * CompanyProductServices generated by hbm2java
 */
@Entity
@Table(name="Company_Product_Services"
    ,catalog="Project_DB"
)
public class CompanyProductServices  implements java.io.Serializable {


     private Integer companyProSerId;
     private Companies companies;
     private int companyProductName;
     private int companyServiceName;
     private Integer companyDescription;

    public CompanyProductServices() {
    }

	
    public CompanyProductServices(Companies companies, int companyProductName, int companyServiceName) {
        this.companies = companies;
        this.companyProductName = companyProductName;
        this.companyServiceName = companyServiceName;
    }
    public CompanyProductServices(Companies companies, int companyProductName, int companyServiceName, Integer companyDescription) {
       this.companies = companies;
       this.companyProductName = companyProductName;
       this.companyServiceName = companyServiceName;
       this.companyDescription = companyDescription;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="Company_pro_ser_id", unique=true, nullable=false)
    public Integer getCompanyProSerId() {
        return this.companyProSerId;
    }
    
    public void setCompanyProSerId(Integer companyProSerId) {
        this.companyProSerId = companyProSerId;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="Company_Id", nullable=false)
    public Companies getCompanies() {
        return this.companies;
    }
    
    public void setCompanies(Companies companies) {
        this.companies = companies;
    }

    
    @Column(name="Company_Product_name", nullable=false)
    public int getCompanyProductName() {
        return this.companyProductName;
    }
    
    public void setCompanyProductName(int companyProductName) {
        this.companyProductName = companyProductName;
    }

    
    @Column(name="Company_Service_Name", nullable=false)
    public int getCompanyServiceName() {
        return this.companyServiceName;
    }
    
    public void setCompanyServiceName(int companyServiceName) {
        this.companyServiceName = companyServiceName;
    }

    
    @Column(name="Company_Description")
    public Integer getCompanyDescription() {
        return this.companyDescription;
    }
    
    public void setCompanyDescription(Integer companyDescription) {
        this.companyDescription = companyDescription;
    }




}


