package com.mycompany.entity;
// Generated Feb 23, 2018 5:59:52 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Countries generated by hbm2java
 */
@Entity
@Table(name="Countries"
    ,catalog="Project_DB"
)
public class Countries  implements java.io.Serializable {


     private Integer countryId;
     private Continetes continetes;
     private String countryCode;
     private String countryName;
     private String countryDesc;
     private Set<Governrates> governrateses = new HashSet<Governrates>(0);
     private Set<Cities> citieses = new HashSet<Cities>(0);
     private Set<Addresses> addresseses = new HashSet<Addresses>(0);

    public Countries() {
    }

	
    public Countries(Continetes continetes, String countryCode, String countryName) {
        this.continetes = continetes;
        this.countryCode = countryCode;
        this.countryName = countryName;
    }
    public Countries(Continetes continetes, String countryCode, String countryName, String countryDesc, Set<Governrates> governrateses, Set<Cities> citieses, Set<Addresses> addresseses) {
       this.continetes = continetes;
       this.countryCode = countryCode;
       this.countryName = countryName;
       this.countryDesc = countryDesc;
       this.governrateses = governrateses;
       this.citieses = citieses;
       this.addresseses = addresseses;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="country_id", unique=true, nullable=false)
    public Integer getCountryId() {
        return this.countryId;
    }
    
    public void setCountryId(Integer countryId) {
        this.countryId = countryId;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="Continent_Id", nullable=false)
    public Continetes getContinetes() {
        return this.continetes;
    }
    
    public void setContinetes(Continetes continetes) {
        this.continetes = continetes;
    }

    
    @Column(name="Country_Code", nullable=false)
    public String getCountryCode() {
        return this.countryCode;
    }
    
    public void setCountryCode(String countryCode) {
        this.countryCode = countryCode;
    }

    
    @Column(name="country_Name", nullable=false)
    public String getCountryName() {
        return this.countryName;
    }
    
    public void setCountryName(String countryName) {
        this.countryName = countryName;
    }

    
    @Column(name="Country_Desc", length=300)
    public String getCountryDesc() {
        return this.countryDesc;
    }
    
    public void setCountryDesc(String countryDesc) {
        this.countryDesc = countryDesc;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="countries")
    public Set<Governrates> getGovernrateses() {
        return this.governrateses;
    }
    
    public void setGovernrateses(Set<Governrates> governrateses) {
        this.governrateses = governrateses;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="countries")
    public Set<Cities> getCitieses() {
        return this.citieses;
    }
    
    public void setCitieses(Set<Cities> citieses) {
        this.citieses = citieses;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="countries")
    public Set<Addresses> getAddresseses() {
        return this.addresseses;
    }
    
    public void setAddresseses(Set<Addresses> addresseses) {
        this.addresseses = addresseses;
    }




}


