package com.mycompany.entity;
// Generated Feb 23, 2018 5:59:52 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * DepartmentsCompanies generated by hbm2java
 */
@Entity
@Table(name="Departments_Companies"
    ,catalog="Project_DB"
)
public class DepartmentsCompanies  implements java.io.Serializable {


     private Integer departmentId;
     private Companies companies;
     private Status status;
     private String departmentName;
     private String departmentSpecification;
     private Integer departmentDesc;
     private Set<Employees> employeeses = new HashSet<Employees>(0);

    public DepartmentsCompanies() {
    }

	
    public DepartmentsCompanies(Companies companies, Status status, String departmentName, String departmentSpecification) {
        this.companies = companies;
        this.status = status;
        this.departmentName = departmentName;
        this.departmentSpecification = departmentSpecification;
    }
    public DepartmentsCompanies(Companies companies, Status status, String departmentName, String departmentSpecification, Integer departmentDesc, Set<Employees> employeeses) {
       this.companies = companies;
       this.status = status;
       this.departmentName = departmentName;
       this.departmentSpecification = departmentSpecification;
       this.departmentDesc = departmentDesc;
       this.employeeses = employeeses;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="Department_Id", unique=true, nullable=false)
    public Integer getDepartmentId() {
        return this.departmentId;
    }
    
    public void setDepartmentId(Integer departmentId) {
        this.departmentId = departmentId;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="Companies_Company_Id", nullable=false)
    public Companies getCompanies() {
        return this.companies;
    }
    
    public void setCompanies(Companies companies) {
        this.companies = companies;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="Status_Id", nullable=false)
    public Status getStatus() {
        return this.status;
    }
    
    public void setStatus(Status status) {
        this.status = status;
    }

    
    @Column(name="Department_Name", nullable=false)
    public String getDepartmentName() {
        return this.departmentName;
    }
    
    public void setDepartmentName(String departmentName) {
        this.departmentName = departmentName;
    }

    
    @Column(name="Department_Specification", nullable=false)
    public String getDepartmentSpecification() {
        return this.departmentSpecification;
    }
    
    public void setDepartmentSpecification(String departmentSpecification) {
        this.departmentSpecification = departmentSpecification;
    }

    
    @Column(name="Department_Desc")
    public Integer getDepartmentDesc() {
        return this.departmentDesc;
    }
    
    public void setDepartmentDesc(Integer departmentDesc) {
        this.departmentDesc = departmentDesc;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="departmentsCompanies")
    public Set<Employees> getEmployeeses() {
        return this.employeeses;
    }
    
    public void setEmployeeses(Set<Employees> employeeses) {
        this.employeeses = employeeses;
    }




}


