package com.mycompany.entity;
// Generated Feb 23, 2018 5:59:52 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Departments generated by hbm2java
 */
@Entity
@Table(name="Departments"
    ,catalog="Project_DB"
)
public class Departments  implements java.io.Serializable {


     private Integer departmentId;
     private String departmentName;
     private String departmentCode;
     private String departmentSpecification;
     private String departmentDesc;
     private Set<UsersAppUserUs> usersAppUserUses = new HashSet<UsersAppUserUs>(0);

    public Departments() {
    }

	
    public Departments(String departmentName, String departmentCode, String departmentSpecification) {
        this.departmentName = departmentName;
        this.departmentCode = departmentCode;
        this.departmentSpecification = departmentSpecification;
    }
    public Departments(String departmentName, String departmentCode, String departmentSpecification, String departmentDesc, Set<UsersAppUserUs> usersAppUserUses) {
       this.departmentName = departmentName;
       this.departmentCode = departmentCode;
       this.departmentSpecification = departmentSpecification;
       this.departmentDesc = departmentDesc;
       this.usersAppUserUses = usersAppUserUses;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="Department_id", unique=true, nullable=false)
    public Integer getDepartmentId() {
        return this.departmentId;
    }
    
    public void setDepartmentId(Integer departmentId) {
        this.departmentId = departmentId;
    }

    
    @Column(name="Department_Name", nullable=false)
    public String getDepartmentName() {
        return this.departmentName;
    }
    
    public void setDepartmentName(String departmentName) {
        this.departmentName = departmentName;
    }

    
    @Column(name="Department_Code", nullable=false)
    public String getDepartmentCode() {
        return this.departmentCode;
    }
    
    public void setDepartmentCode(String departmentCode) {
        this.departmentCode = departmentCode;
    }

    
    @Column(name="Department_specification", nullable=false)
    public String getDepartmentSpecification() {
        return this.departmentSpecification;
    }
    
    public void setDepartmentSpecification(String departmentSpecification) {
        this.departmentSpecification = departmentSpecification;
    }

    
    @Column(name="Department_Desc")
    public String getDepartmentDesc() {
        return this.departmentDesc;
    }
    
    public void setDepartmentDesc(String departmentDesc) {
        this.departmentDesc = departmentDesc;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="departments")
    public Set<UsersAppUserUs> getUsersAppUserUses() {
        return this.usersAppUserUses;
    }
    
    public void setUsersAppUserUses(Set<UsersAppUserUs> usersAppUserUses) {
        this.usersAppUserUses = usersAppUserUses;
    }




}


