package com.mycompany.entity;
// Generated Feb 23, 2018 5:59:52 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Gender generated by hbm2java
 */
@Entity
@Table(name="Gender"
    ,catalog="Project_DB"
)
public class Gender  implements java.io.Serializable {


     private Integer genderId;
     private String genderName;
     private String genderDesc;
     private Set<Employees> employeeses = new HashSet<Employees>(0);
     private Set<UsersAppUserUs> usersAppUserUses = new HashSet<UsersAppUserUs>(0);

    public Gender() {
    }

	
    public Gender(String genderName) {
        this.genderName = genderName;
    }
    public Gender(String genderName, String genderDesc, Set<Employees> employeeses, Set<UsersAppUserUs> usersAppUserUses) {
       this.genderName = genderName;
       this.genderDesc = genderDesc;
       this.employeeses = employeeses;
       this.usersAppUserUses = usersAppUserUses;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="Gender_Id", unique=true, nullable=false)
    public Integer getGenderId() {
        return this.genderId;
    }
    
    public void setGenderId(Integer genderId) {
        this.genderId = genderId;
    }

    
    @Column(name="Gender_Name", nullable=false)
    public String getGenderName() {
        return this.genderName;
    }
    
    public void setGenderName(String genderName) {
        this.genderName = genderName;
    }

    
    @Column(name="Gender_Desc")
    public String getGenderDesc() {
        return this.genderDesc;
    }
    
    public void setGenderDesc(String genderDesc) {
        this.genderDesc = genderDesc;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="gender")
    public Set<Employees> getEmployeeses() {
        return this.employeeses;
    }
    
    public void setEmployeeses(Set<Employees> employeeses) {
        this.employeeses = employeeses;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="gender")
    public Set<UsersAppUserUs> getUsersAppUserUses() {
        return this.usersAppUserUses;
    }
    
    public void setUsersAppUserUses(Set<UsersAppUserUs> usersAppUserUses) {
        this.usersAppUserUses = usersAppUserUses;
    }




}


