package com.mycompany.entity;
// Generated Feb 23, 2018 5:59:52 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Governrates generated by hbm2java
 */
@Entity
@Table(name="Governrates"
    ,catalog="Project_DB"
)
public class Governrates  implements java.io.Serializable {


     private Integer governorateId;
     private Countries countries;
     private String governorateCode;
     private String governorateName;
     private String governorateDesc;
     private Set<Addresses> addresseses = new HashSet<Addresses>(0);
     private Set<Districtd> districtds = new HashSet<Districtd>(0);

    public Governrates() {
    }

	
    public Governrates(Countries countries, String governorateName) {
        this.countries = countries;
        this.governorateName = governorateName;
    }
    public Governrates(Countries countries, String governorateCode, String governorateName, String governorateDesc, Set<Addresses> addresseses, Set<Districtd> districtds) {
       this.countries = countries;
       this.governorateCode = governorateCode;
       this.governorateName = governorateName;
       this.governorateDesc = governorateDesc;
       this.addresseses = addresseses;
       this.districtds = districtds;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="governorate_Id", unique=true, nullable=false)
    public Integer getGovernorateId() {
        return this.governorateId;
    }
    
    public void setGovernorateId(Integer governorateId) {
        this.governorateId = governorateId;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="country_id", nullable=false)
    public Countries getCountries() {
        return this.countries;
    }
    
    public void setCountries(Countries countries) {
        this.countries = countries;
    }

    
    @Column(name="governorate_code")
    public String getGovernorateCode() {
        return this.governorateCode;
    }
    
    public void setGovernorateCode(String governorateCode) {
        this.governorateCode = governorateCode;
    }

    
    @Column(name="governorate_Name", nullable=false)
    public String getGovernorateName() {
        return this.governorateName;
    }
    
    public void setGovernorateName(String governorateName) {
        this.governorateName = governorateName;
    }

    
    @Column(name="governorate_desc", length=300)
    public String getGovernorateDesc() {
        return this.governorateDesc;
    }
    
    public void setGovernorateDesc(String governorateDesc) {
        this.governorateDesc = governorateDesc;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="governrates")
    public Set<Addresses> getAddresseses() {
        return this.addresseses;
    }
    
    public void setAddresseses(Set<Addresses> addresseses) {
        this.addresseses = addresseses;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="governrates")
    public Set<Districtd> getDistrictds() {
        return this.districtds;
    }
    
    public void setDistrictds(Set<Districtd> districtds) {
        this.districtds = districtds;
    }




}


