package com.mycompany.entity;
// Generated Feb 23, 2018 5:59:52 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Status generated by hbm2java
 */
@Entity
@Table(name="Status"
    ,catalog="Project_DB"
)
public class Status  implements java.io.Serializable {


     private Integer statusId;
     private String statusTitle;
     private Integer statusDesc;
     private Set<Companies> companieses = new HashSet<Companies>(0);
     private Set<Employees> employeeses = new HashSet<Employees>(0);
     private Set<DepartmentsCompanies> departmentsCompanieses = new HashSet<DepartmentsCompanies>(0);

    public Status() {
    }

	
    public Status(String statusTitle) {
        this.statusTitle = statusTitle;
    }
    public Status(String statusTitle, Integer statusDesc, Set<Companies> companieses, Set<Employees> employeeses, Set<DepartmentsCompanies> departmentsCompanieses) {
       this.statusTitle = statusTitle;
       this.statusDesc = statusDesc;
       this.companieses = companieses;
       this.employeeses = employeeses;
       this.departmentsCompanieses = departmentsCompanieses;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="Status_Id", unique=true, nullable=false)
    public Integer getStatusId() {
        return this.statusId;
    }
    
    public void setStatusId(Integer statusId) {
        this.statusId = statusId;
    }

    
    @Column(name="Status_Title", nullable=false)
    public String getStatusTitle() {
        return this.statusTitle;
    }
    
    public void setStatusTitle(String statusTitle) {
        this.statusTitle = statusTitle;
    }

    
    @Column(name="Status_Desc")
    public Integer getStatusDesc() {
        return this.statusDesc;
    }
    
    public void setStatusDesc(Integer statusDesc) {
        this.statusDesc = statusDesc;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="status")
    public Set<Companies> getCompanieses() {
        return this.companieses;
    }
    
    public void setCompanieses(Set<Companies> companieses) {
        this.companieses = companieses;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="status")
    public Set<Employees> getEmployeeses() {
        return this.employeeses;
    }
    
    public void setEmployeeses(Set<Employees> employeeses) {
        this.employeeses = employeeses;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="status")
    public Set<DepartmentsCompanies> getDepartmentsCompanieses() {
        return this.departmentsCompanieses;
    }
    
    public void setDepartmentsCompanieses(Set<DepartmentsCompanies> departmentsCompanieses) {
        this.departmentsCompanieses = departmentsCompanieses;
    }




}


