package com.mycompany.entity;
// Generated Feb 23, 2018 5:59:52 AM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Technology generated by hbm2java
 */
@Entity
@Table(name="Technology"
    ,catalog="Project_DB"
)
public class Technology  implements java.io.Serializable {


     private Integer companyTechnologyId;
     private Employees employees;
     private int companyTechnologyName;
     private Integer companyTechnologyDesc;

    public Technology() {
    }

	
    public Technology(Employees employees, int companyTechnologyName) {
        this.employees = employees;
        this.companyTechnologyName = companyTechnologyName;
    }
    public Technology(Employees employees, int companyTechnologyName, Integer companyTechnologyDesc) {
       this.employees = employees;
       this.companyTechnologyName = companyTechnologyName;
       this.companyTechnologyDesc = companyTechnologyDesc;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="Company_Technology_Id", unique=true, nullable=false)
    public Integer getCompanyTechnologyId() {
        return this.companyTechnologyId;
    }
    
    public void setCompanyTechnologyId(Integer companyTechnologyId) {
        this.companyTechnologyId = companyTechnologyId;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="Employee_Id", nullable=false)
    public Employees getEmployees() {
        return this.employees;
    }
    
    public void setEmployees(Employees employees) {
        this.employees = employees;
    }

    
    @Column(name="Company_technology_Name", nullable=false)
    public int getCompanyTechnologyName() {
        return this.companyTechnologyName;
    }
    
    public void setCompanyTechnologyName(int companyTechnologyName) {
        this.companyTechnologyName = companyTechnologyName;
    }

    
    @Column(name="Company_technology_Desc")
    public Integer getCompanyTechnologyDesc() {
        return this.companyTechnologyDesc;
    }
    
    public void setCompanyTechnologyDesc(Integer companyTechnologyDesc) {
        this.companyTechnologyDesc = companyTechnologyDesc;
    }




}


