package com.mycompany.entity;
// Generated Feb 23, 2018 5:59:52 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * TypeCompanies generated by hbm2java
 */
@Entity
@Table(name="Type_Companies"
    ,catalog="Project_DB"
)
public class TypeCompanies  implements java.io.Serializable {


     private Integer companyIdType;
     private int companyTypeName;
     private Integer companyDesc;
     private Set<Companies> companieses = new HashSet<Companies>(0);

    public TypeCompanies() {
    }

	
    public TypeCompanies(int companyTypeName) {
        this.companyTypeName = companyTypeName;
    }
    public TypeCompanies(int companyTypeName, Integer companyDesc, Set<Companies> companieses) {
       this.companyTypeName = companyTypeName;
       this.companyDesc = companyDesc;
       this.companieses = companieses;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="company_id_type", unique=true, nullable=false)
    public Integer getCompanyIdType() {
        return this.companyIdType;
    }
    
    public void setCompanyIdType(Integer companyIdType) {
        this.companyIdType = companyIdType;
    }

    
    @Column(name="Company_Type_Name", nullable=false)
    public int getCompanyTypeName() {
        return this.companyTypeName;
    }
    
    public void setCompanyTypeName(int companyTypeName) {
        this.companyTypeName = companyTypeName;
    }

    
    @Column(name="Company_Desc")
    public Integer getCompanyDesc() {
        return this.companyDesc;
    }
    
    public void setCompanyDesc(Integer companyDesc) {
        this.companyDesc = companyDesc;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="typeCompanies")
    public Set<Companies> getCompanieses() {
        return this.companieses;
    }
    
    public void setCompanieses(Set<Companies> companieses) {
        this.companieses = companieses;
    }




}


