package com.mycompany.entity;
// Generated Feb 23, 2018 5:59:52 AM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * UsersImages generated by hbm2java
 */
@Entity
@Table(name="Users_Images"
    ,catalog="Project_DB"
)
public class UsersImages  implements java.io.Serializable {


     private Integer userImageId;
     private UsersAppUserUs usersAppUserUs;
     private String userImagePath;
     private String userImageCardIdPath;
     private String userImageDesc;

    public UsersImages() {
    }

	
    public UsersImages(UsersAppUserUs usersAppUserUs, String userImagePath, String userImageCardIdPath) {
        this.usersAppUserUs = usersAppUserUs;
        this.userImagePath = userImagePath;
        this.userImageCardIdPath = userImageCardIdPath;
    }
    public UsersImages(UsersAppUserUs usersAppUserUs, String userImagePath, String userImageCardIdPath, String userImageDesc) {
       this.usersAppUserUs = usersAppUserUs;
       this.userImagePath = userImagePath;
       this.userImageCardIdPath = userImageCardIdPath;
       this.userImageDesc = userImageDesc;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="User_Image_Id", unique=true, nullable=false)
    public Integer getUserImageId() {
        return this.userImageId;
    }
    
    public void setUserImageId(Integer userImageId) {
        this.userImageId = userImageId;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="User_id", nullable=false)
    public UsersAppUserUs getUsersAppUserUs() {
        return this.usersAppUserUs;
    }
    
    public void setUsersAppUserUs(UsersAppUserUs usersAppUserUs) {
        this.usersAppUserUs = usersAppUserUs;
    }

    
    @Column(name="User_Image_Path", nullable=false)
    public String getUserImagePath() {
        return this.userImagePath;
    }
    
    public void setUserImagePath(String userImagePath) {
        this.userImagePath = userImagePath;
    }

    
    @Column(name="User_Image_CardID_Path", nullable=false)
    public String getUserImageCardIdPath() {
        return this.userImageCardIdPath;
    }
    
    public void setUserImageCardIdPath(String userImageCardIdPath) {
        this.userImageCardIdPath = userImageCardIdPath;
    }

    
    @Column(name="User_Image_Desc")
    public String getUserImageDesc() {
        return this.userImageDesc;
    }
    
    public void setUserImageDesc(String userImageDesc) {
        this.userImageDesc = userImageDesc;
    }




}


